require 'rails_helper'

describe Holidays do
  it 'lists the next 3 holidays' do
    days = Holidays.next_three('US')

    expect(days).to eq([{"date"=>"2021-07-05",
  "localName"=>"Independence Day",
  "name"=>"Independence Day",
  "countryCode"=>"US",
  "fixed"=>false,
  "global"=>true,
  "counties"=>nil,
  "launchYear"=>nil,
  "types"=>["Public"]},
 {"date"=>"2021-09-06",
  "localName"=>"Labor Day",
  "name"=>"Labour Day",
  "countryCode"=>"US",
  "fixed"=>false,
  "global"=>true,
  "counties"=>nil,
  "launchYear"=>nil,
  "types"=>["Public"]},
 {"date"=>"2021-10-11",
  "localName"=>"Columbus Day",
  "name"=>"Columbus Day",
  "countryCode"=>"US",
  "fixed"=>false,
  "global"=>false,
  "counties"=>
   ["US-AL",
    "US-AZ",
    "US-CO",
    "US-CT",
    "US-DC",
    "US-GA",
    "US-ID",
    "US-IL",
    "US-IN",
    "US-IA",
    "US-KS",
    "US-KY",
    "US-LA",
    "US-ME",
    "US-MD",
    "US-MA",
    "US-MS",
    "US-MO",
    "US-MT",
    "US-NE",
    "US-NH",
    "US-NJ",
    "US-NM",
    "US-NY",
    "US-NC",
    "US-OH",
    "US-OK",
    "US-PA",
    "US-RI",
    "US-SC",
    "US-TN",
    "US-UT",
    "US-VA",
    "US-WV"],
  "launchYear"=>nil,
  "types"=>["Public"]}])
  end
end