require 'rails_helper'

describe NagerService do
  it 'returns holidays for country code' do
    holidays = NagerService.holidays('US')

    expect(holidays).to eq [{"date"=>"2021-01-01",
    "localName"=>"New Year's Day",
    "name"=>"New Year's Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-01-18",
    "localName"=>"Martin Luther King, Jr. Day",
    "name"=>"Martin Luther King, Jr. Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-01-20",
    "localName"=>"Inauguration Day",
    "name"=>"Inauguration Day",
    "countryCode"=>"US",
    "fixed"=>true,
    "global"=>false,
    "counties"=>["US-DC", "US-LA", "US-MD", "US-VA"],
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-02-15",
    "localName"=>"Presidents Day",
    "name"=>"Washington's Birthday",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-05-31",
    "localName"=>"Memorial Day",
    "name"=>"Memorial Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-07-05",
    "localName"=>"Independence Day",
    "name"=>"Independence Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-09-06",
    "localName"=>"Labor Day",
    "name"=>"Labour Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-10-11",
    "localName"=>"Columbus Day",
    "name"=>"Columbus Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>false,
    "counties"=>
    ["US-AL",
      "US-AZ",
      "US-CO",
      "US-CT",
      "US-DC",
      "US-GA",
      "US-ID",
      "US-IL",
      "US-IN",
      "US-IA",
      "US-KS",
      "US-KY",
      "US-LA",
      "US-ME",
      "US-MD",
      "US-MA",
      "US-MS",
      "US-MO",
      "US-MT",
      "US-NE",
      "US-NH",
      "US-NJ",
      "US-NM",
      "US-NY",
      "US-NC",
      "US-OH",
      "US-OK",
      "US-PA",
      "US-RI",
      "US-SC",
      "US-TN",
      "US-UT",
      "US-VA",
      "US-WV"],
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-11-11",
    "localName"=>"Veterans Day",
    "name"=>"Veterans Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-11-25",
    "localName"=>"Thanksgiving Day",
    "name"=>"Thanksgiving Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>1863,
    "types"=>["Public"]},
  {"date"=>"2021-12-24",
    "localName"=>"Christmas Day",
    "name"=>"Christmas Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]}]
  end

  it 'accepts railshelper stub' do
    holidays = NagerService.holidays('AT')

    expect(holidays).to eq [{"date"=>"2021-01-01",
    "localName"=>"New Year's Day",
    "name"=>"New Year's Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-01-18",
    "localName"=>"Martin Luther King, Jr. Day",
    "name"=>"Martin Luther King, Jr. Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-01-20",
    "localName"=>"Inauguration Day",
    "name"=>"Inauguration Day",
    "countryCode"=>"US",
    "fixed"=>true,
    "global"=>false,
    "counties"=>["US-DC", "US-LA", "US-MD", "US-VA"],
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-02-15",
    "localName"=>"Presidents Day",
    "name"=>"Washington's Birthday",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-05-31",
    "localName"=>"Memorial Day",
    "name"=>"Memorial Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-07-05",
    "localName"=>"Independence Day",
    "name"=>"Independence Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-09-06",
    "localName"=>"Labor Day",
    "name"=>"Labour Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-10-11",
    "localName"=>"Columbus Day",
    "name"=>"Columbus Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>false,
    "counties"=>
    ["US-AL",
      "US-AZ",
      "US-CO",
      "US-CT",
      "US-DC",
      "US-GA",
      "US-ID",
      "US-IL",
      "US-IN",
      "US-IA",
      "US-KS",
      "US-KY",
      "US-LA",
      "US-ME",
      "US-MD",
      "US-MA",
      "US-MS",
      "US-MO",
      "US-MT",
      "US-NE",
      "US-NH",
      "US-NJ",
      "US-NM",
      "US-NY",
      "US-NC",
      "US-OH",
      "US-OK",
      "US-PA",
      "US-RI",
      "US-SC",
      "US-TN",
      "US-UT",
      "US-VA",
      "US-WV"],
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-11-11",
    "localName"=>"Veterans Day",
    "name"=>"Veterans Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]},
  {"date"=>"2021-11-25",
    "localName"=>"Thanksgiving Day",
    "name"=>"Thanksgiving Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>1863,
    "types"=>["Public"]},
  {"date"=>"2021-12-24",
    "localName"=>"Christmas Day",
    "name"=>"Christmas Day",
    "countryCode"=>"US",
    "fixed"=>false,
    "global"=>true,
    "counties"=>nil,
    "launchYear"=>nil,
    "types"=>["Public"]}]
  end
end